Project related
SciFin-Team/SciFin pull request #4
Opened 2020-09-04 19:11 UTC by FabienNugier

Add new files to project and add a new Readme section.

2020-09-05 21:15 UTC, kkontoudi requested changes
I think you should also add __pycahe__ in the .gitignore.
I have plenty of those when I execute ``git status``

2020-09-05 21:38 UTC, FabienNugier commented
Done! Should be better now.

2020-09-05 23:56 UTC, kkontoudi approved these changes

2020-09-06 08:18 UTC, FabienNugier commented
Added files to versioning and modified Readme.

2020-09-06 08:19 UTC, merged